<NotepadPlus>
    <Session activeView="1">
        <mainView activeIndex="8">
            <File firstVisibleLine="36" xOffset="0" scrollWidth="1620" startPos="3084" endPos="3094" selMode="0" lang="JavaScript" encoding="-1" filename="C:\wamp\www\MyJs\MyJs.js" backupFilePath="" originalFileLastModifTimestamp="1344866666" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16777217" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="14" xOffset="0" scrollWidth="3900" startPos="47" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\index.php" backupFilePath="" originalFileLastModifTimestamp="1558144572" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="6" xOffset="0" scrollWidth="3900" startPos="597" endPos="597" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\MyPhp\Validate.php" backupFilePath="" originalFileLastModifTimestamp="1558149396" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="21" xOffset="0" scrollWidth="760" startPos="851" endPos="867" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\MyPhp\Validate.class.php" backupFilePath="" originalFileLastModifTimestamp="1341567662" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="239" xOffset="0" scrollWidth="5160" startPos="10094" endPos="10094" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\MyPhp\Manipulate.class.php" backupFilePath="" originalFileLastModifTimestamp="1558147064" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="350" startPos="141" endPos="141" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\MyPhp\config.php" backupFilePath="" originalFileLastModifTimestamp="1558146749" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1510" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\Admin\userPage.php" backupFilePath="" originalFileLastModifTimestamp="1328251722" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="20" xOffset="0" scrollWidth="3900" startPos="476" endPos="482" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\Admin\home.php" backupFilePath="" originalFileLastModifTimestamp="1328866124" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="17" xOffset="0" scrollWidth="3900" startPos="744" endPos="744" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\User\CreateReport.php" backupFilePath="" originalFileLastModifTimestamp="1558151352" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0">
            <File firstVisibleLine="5" xOffset="0" scrollWidth="3960" startPos="1077" endPos="1090" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp\www\User\User.php" backupFilePath="" originalFileLastModifTimestamp="1558149755" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7536741" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="299" xOffset="0" scrollWidth="3960" startPos="5149" endPos="5158" selMode="0" lang="CSS" encoding="-1" filename="C:\wamp\www\MyCss\MyCss.css" backupFilePath="" originalFileLastModifTimestamp="1341568346" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
        </subView>
    </Session>
</NotepadPlus>
